name: agro_pharm_application
description: "A new Flutter project."
publish_to: 'none'  # Remova esta linha se desejar publicar no pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.4.0
  path: ^1.9.0
  sqflite_common_ffi: 2.3.4  # Adicionar apenas na seção dependencies se necessário para o app

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  # Usado para linter e boas práticas de código

flutter:
  uses-material-design: true
